[package]
name = "tiny-fe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
crossterm = "0.28.1"
ratatui = "0.28.1"

[dev-dependencies]
tempfile = "3.13.0"
